"""Create the updated white paper DOCX."""
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(11)

def h1(t): doc.add_heading(t, level=1)
def h2(t): doc.add_heading(t, level=2)
def para(t, bold=False, italic=False):
    p = doc.add_paragraph()
    r = p.add_run(t)
    r.bold = bold
    r.italic = italic
def bullet(t): doc.add_paragraph(t, style='List Bullet')
def numbered(t): doc.add_paragraph(t, style='List Number')

# Title
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run("AI-Powered Self-Healing IT Infrastructure\nfor Energy & Utilities Companies")
r.bold = True
r.font.size = Pt(18)
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run("When Your Billing System Crashes at 3 AM, Who Fixes It?")
r.italic = True
r.font.size = Pt(14)
doc.add_paragraph()
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run("Author: Ravindra Yadav\nAffiliation: IBM\nContact: ravindya@in.ibm.com\n\nSubmission: Communication Sector Summit 2026")
r.font.size = Pt(10)
doc.add_paragraph()

h1("The Problem Nobody Talks About")
para("Picture this: It\u2019s 3:14 AM on the last day of the billing cycle. The meter data management server at a regional utility hits 95% CPU. An alert fires. An on-call IT engineer\u2019s phone buzzes. They wake up, VPN into the corporate network, SSH into the server, diagnose the issue (a runaway batch process consuming all available CPU), kill the process, restart the service, verify it\u2019s healthy, document what happened, and go back to sleep. Total time: 35 minutes.")
para("Now multiply that by 200\u2013400 infrastructure alerts per day across all the IT systems that keep a utility running \u2014 billing, customer portals, workforce management, outage management, and ERP. That\u2019s the reality for IT operations teams in energy and utilities companies today.")
para("Energy and utilities companies rely on dozens of business-critical IT applications. The billing system that processes millions of customer accounts. The customer self-service portal that handles payments and service requests. The meter data management platform ingesting readings from smart meters every 15 minutes. When any of these experience infrastructure problems \u2014 disk full, service crash, memory exhaustion \u2014 the current response is entirely manual.")
para("This approach has three fundamental problems:")
para("It\u2019s slow. The mean time to resolve a routine IT infrastructure incident is 25\u201340 minutes. During that time, billing jobs stall, customers can\u2019t access their accounts, meter data queues back up, and SLA clocks are ticking.")
para("It doesn\u2019t scale. During month-end billing runs, alert volume spikes 5\u201310x. IT engineers experience alert fatigue \u2014 research shows they start ignoring alerts after 20+ in a single shift. Critical issues get lost in the noise.")
para("It introduces risk. 23% of extended outages are caused by incorrect manual remediation \u2014 a typo in a restart command, a fix applied to the wrong environment, a service restarted without draining connections.")
para("")
para("The question we set out to answer: What if your IT infrastructure could diagnose and fix routine application problems itself \u2014 with human oversight but without human delay?", italic=True)

h1("Our Approach: Agentic AI Meets IT Operations")
para("We built a system that sits between your monitoring tools and your IT infrastructure. It watches for problems, figures out what\u2019s wrong, proposes a fix, asks an IT operator for permission, and then executes the fix \u2014 all within minutes, not hours.")
para("The key insight is that most IT incidents in utilities are routine and repetitive. The same billing server running out of disk space every month-end. The same customer portal crashing under load. These don\u2019t need a senior engineer\u2019s diagnosis \u2014 they need fast, consistent execution of a known fix.")

h2("The Seven-Step Pipeline")
para("Step 1: Detect", bold=True)
para("CloudWatch continuously monitors every server\u2019s CPU, memory, disk, and service health. When a metric crosses a threshold, an alarm triggers within 60 seconds. The alert flows through SNS to a Lambda that delivers it to our ECS service via API Gateway.")
para("Step 2: Understand", bold=True)
para("A raw alert like \u201chigh CPU on 10.0.5.22\u201d isn\u2019t useful alone. The system enriches it: that server hosts Meter Data Management, owned by Revenue IT, processing data for 2 million customers. Now we know the business impact.")
para("Step 3: Decide", bold=True)
para("Two decision paths:")
bullet("Known Problem: Matching playbook (proven fix). \u201cHigh CPU on billing server\u201d \u2192 fix_high_cpu.yml.")
bullet("New Problem: AI Reasoning Agent invokes Amazon Bedrock. Intelligent model router selects cheapest capable model: Nova Lite for simple (70%), Nova Pro for moderate (20%), Claude Sonnet for complex (10%). Saves 60\u201390% on AI costs.")
para("Step 4: Safety Check", bold=True)
para("7-layer guardrail engine with short-circuit semantics:")
numbered("Self-Protection: Never remediate automation infrastructure or databases.")
numbered("Maintenance Windows: No actions during planned change windows.")
numbered("Circuit Breakers: 3 failures in 5 minutes \u2192 stop and alert humans.")
numbered("Concurrency Control: One fix per server at a time.")
numbered("Blast Radius Classification: nginx restart (low) vs. billing DB (critical).")
numbered("Health Verification: Check downstream dependencies before executing.")
numbered("Human Approval: Final gate for high-risk actions.")
para("Plus: AI Plan Validator blocks dangerous commands (rm -rf, shutdown, iptables flush). Fleet circuit breaker pauses ALL automation if 5+ failures across any hosts in 5 minutes.")

para("Step 5: Approve", bold=True)
para("Nothing executes without human consent. The operator gets an email with root cause analysis, proposed fix, and a one-click \u201cApprove\u201d button. Token is HMAC-signed, DynamoDB-stored, 30-minute expiry. Two-step design (GET confirm page \u2192 POST execute) prevents email scanner auto-approval. Exactly-once consumption via conditional writes.")
para("Step 6: Heal", bold=True)
para("Executes via AWS Systems Manager \u2014 no SSH keys, no open ports. Stop conditions monitor CloudWatch every 10 seconds during execution. If remediation makes things worse (healthy hosts drop to zero, 5xx spike), auto-abort. Ansible playbooks with 300s timeout and SIGTERM/SIGKILL escalation.")
para("Step 7: Verify & Learn", bold=True)
para("Baking validation confirms alarm resolves and host recovers. Outcome (success/failure/timeout/ineffective) stored in DynamoDB. Feeds back into model router \u2014 system continuously improves. Full cycle: under 3 minutes for known problems.", bold=True)

h1("What Makes This Different")
h2("Intelligence That Learns")
para("The AI learns from history. The billing disk cleanup that works every month gets routed to the cheapest model (Nova Lite, $0.0003). A new alert never seen before gets full Claude Sonnet reasoning. An alert where all past fixes failed gets escalated with full context. The effectiveness scorer continuously tracks which playbooks work.")
h2("Safety First, Always")
para("Defense-in-depth beyond the 7-layer engine:")
bullet("Fleet circuit breaker: 5 failures in 5 min across any hosts \u2192 ALL automation pauses.")
bullet("Stop conditions: CloudWatch alarms monitored DURING execution \u2192 auto-abort if system degrades.")
bullet("Baking validation: post-execution monitoring confirms fix actually worked.")
bullet("Plan validator: regex denylist blocks rm -rf, shutdown, iptables flush, chmod 777.")
bullet("Parameter bounds: max 5 hosts, max 10 steps, max 3 AI executions per host per hour.")
bullet("Protected hosts: automation controllers, databases, vaults are untouchable.")
h2("Storm Handling")
para("Storm detector: sliding-window algorithm, groups alerts when rate exceeds 50/min. Only one representative per group processed \u2014 reduces noise 10\u201350x. HTTP 429 when queue full. Alert inhibition: DatabaseDown suppresses APITimeout, ConnectionRefused, HealthCheckFailed.")
h2("Configuration-Driven Operations")
para("12 YAML files control all behavior without code changes: playbook mapping, asset inventory, service dependencies, execution ordering (DAG), risk classification, resource conflicts, denied commands, protected hosts, inhibition rules, maintenance windows, bulkhead limits, stop conditions.")

h1("Architecture & Technology")
para("Runs entirely on AWS, deployed as infrastructure-as-code (6 CDK stacks):")
bullet("Compute: AWS ECS Fargate (serverless containers)")
bullet("AI Reasoning: Amazon Bedrock (Nova Lite/Pro + Claude Sonnet with 4-model fallback)")
bullet("Data: DynamoDB (4 GSIs, TTL, PITR in prod) + SQS with DLQ")
bullet("Execution: AWS Systems Manager (agentless, tag-based targeting)")
bullet("Notifications: Amazon SES (email-based approval)")
bullet("Monitoring: CloudWatch (logs/metrics/alarms, 30/90/365 day retention)")
bullet("Network: VPC with 2 AZs, VPC Endpoints (DynamoDB, S3, SQS, SSM, Bedrock)")
bullet("Security: API Gateway + WAF, Secrets Manager (90-day rotation), IAM least-privilege")
bullet("Deployment: CDK v2, GitHub Actions CI/CD with health gates and auto-rollback")
bullet("Observability: OpenTelemetry tracing, CloudWatch custom metrics namespace")
para("Cost: ~$150/month at rest. Auto-scales during billing cycle peaks.")

h1("Results & Impact")
bullet("MTTR: 25\u201340 min \u2192 under 3 min (80%+ improvement)")
bullet("Alert noise: 1,000 storm alerts \u2192 ~20 actionable groups (95% reduction)")
bullet("AI costs: 60\u201390% savings via intelligent model routing")
bullet("Error rate: Zero incorrect remediations (vs. 23% manual error rate)")
bullet("Coverage: 24/7 automated response without additional headcount")
bullet("Audit: 100% actions traceable with incident_id, timestamps, outcomes")

h1("Benefits for Utility IT Departments")
h2("For the Business")
bullet("Fewer billing delays and customer-facing outages during critical windows")
bullet("Reduced regulatory SLA exposure from faster resolution")
bullet("After-hours coverage without round-the-clock staffing costs")
h2("For IT Operations")
bullet("Engineers focus on modernization, not firefighting repetitive incidents")
bullet("3x alert coverage per engineer without increasing burnout")
bullet("Full audit trail for SOX compliance and change management")
bullet("Ops teams control behavior via 12 YAML files, no code changes needed")
h2("For IT Leadership")
bullet("Reduces tribal knowledge risk \u2014 expertise encoded in automation")
bullet("Measurable MTTR improvement in executive dashboards")
bullet("Frees budget from reactive support toward digital transformation")

h1("Roadmap")
h2("Implemented Today")
bullet("\u2713 Full detect \u2192 diagnose \u2192 approve \u2192 fix \u2192 verify pipeline")
bullet("\u2713 Intelligent model routing (3 tiers) + 4-model fallback chain")
bullet("\u2713 7-layer safety guardrails + fleet breaker + stop conditions + baking validation")
bullet("\u2713 12 YAML config files for operational control without code changes")
bullet("\u2713 Production AWS deployment with CI/CD, health gates, auto-rollback")
bullet("\u2713 OpenTelemetry tracing + CloudWatch metrics + structured JSON logging")
bullet("\u2713 Storm detection, alert inhibition, and grouping during outages")
bullet("\u2713 Tested with utility IT scenarios: billing, CRM, meter data, portals")
h2("Next Phase (Q3\u2013Q4 2026)")
bullet("\u2192 ServiceNow/BMC Helix integration for ITSM change management")
bullet("\u2192 Predictive alerting: fix problems before they impact billing")
bullet("\u2192 AI-generated runbooks from successful manual resolutions")
bullet("\u2192 Teams/Slack-based approval for faster off-hours response")
bullet("\u2192 Multi-cloud support (Azure Monitor, GCP Cloud Monitoring)")
h2("Vision")
para("The future utility IT department has 10 engineers managing what used to require 40 \u2014 because the infrastructure fixes routine problems itself. IT teams shift from firefighting to what actually matters: cloud migration, digital transformation, and customer experience.")

h1("Conclusion")
para("Utility IT departments can\u2019t afford to keep throwing engineers at infrastructure problems that machines can solve faster and more reliably. But they also can\u2019t afford to hand over control to fully autonomous systems \u2014 the regulatory environment and critical nature of utility operations demands human oversight.")
para("Our approach threads the needle: AI does the fast, repetitive diagnosis work. Humans retain approval authority. Seven layers of safety guardrails prevent catastrophic mistakes. A fleet-wide circuit breaker provides the ultimate safety net. And the system gets smarter with every incident, continuously reducing costs and improving accuracy.")
para("The result: faster resolution, fewer outages, less burnout, and IT infrastructure that genuinely heals itself \u2014 with a human watching over its shoulder.", bold=True)

out = r"c:\Users\RavindraYadav\Documents\AI-Workbook-AWS\production-automation\aiops-production-automation-ansible-agentic\white_paper\Energy_Utilities_IT_Paper_Submission.docx"
doc.save(out)
print(f"Saved: {out}")
